### ISSUE TITLE
onClick event corrupted when using default settings

### ISSUE THREAD

**Issue by pawelgabryelewicz** [schalkt/cookie-warn#1]
Hi! First of all, thanks for this plugin. I was looking for a universal yet simple solution for the cookie bar and this is basically meeting our needs.
Anyway I have noticed that when you don't specify the `data-path` attribute (or just `path` in the config), the button's `onclick` attribute contains invalid JS. If you provide a custom cookie path, the value is wrapped in quotes and everything works fine. The default value (/) however is not wrapped. Invalid syntax causes the accept button to be useless on some browsers.
If something is not clear, please let me know. Thanks!

**Comment by schalkt** [comment]
Hi! Thanks for your feedback. :)
I see the problem and I will fix it soon.

**Comment by schalkt** [comment]
Fixed
